using System.Runtime.InteropServices;

namespace InputSimulator.Native
{
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// <see href="https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-hardwareinput"/>
    /// </remarks>
    [StructLayout(LayoutKind.Sequential)]
    public struct HARDWAREINPUT
    {
        #region Fields
        /// <summary>
        /// The message generated by the input hardware.
        /// </summary>
        public uint uMsg;
        /// <summary>
        /// The low-order word of the lParam parameter for uMsg.
        /// </summary>
        public ushort wParamL;
        /// <summary>
        /// The high-order word of the lParam parameter for uMsg.
        /// </summary>
        public ushort wParamH;
        #endregion Fields
    }
}
