name: Upload NuGet Package

on:
  repository_dispatch:
    types: [ update-package ]
      
defaults:
  run:
    shell: | # Set the default shell for all commands:
           pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
           
jobs:
  build-and-upload:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO:                true
      DOTNET_CLI_TELEMETRY_OPTOUT:  true

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.tag }}
      
      - name: Build
        run: |
          dotnet build -c Release
          
          # Set DocumentationFile
          .\.github\workflows\scripts\SetProperty.ps1  -Path InputSimulator/InputSimulator.csproj  "DocumentationFile=../output/`$`(MSBuildProjectName`).xml"

          dotnet pack InputSimulator/InputSimulator.csproj --noLogo -c Release -o output --include-symbols
              
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget
          path: output/*
          
      - name: Authenticate with Github NuGet Package Registry
        run: dotnet nuget add source --username radj307 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/radj307/index.json"
        
      - name: Upload Package
        run: >
          cd output;
          foreach ($pkg in $(Get-ChildItem -Filter *.nupkg)) {
            dotnet nuget push $pkg.Name -k ${{ github.token }} -s "github" --skip-duplicate
            dotnet nuget push $pkg.Name -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
          }
